public class Country {

    public static String getCountries(){
        return "[  {    \"id\": \"AR\",    \"name\": \"Argentina\",    \"locale\": \"es_AR\",    \"currency_id\": \"ARS\"  },  {    \"id\": \"BR\",    \"name\": \"Brasil\",    \"locale\": \"pt_BR\",    \"currency_id\": \"BRL\"  },  {    \"id\": \"CO\",    \"name\": \"Colombia\",    \"locale\": \"es_CO\",    \"currency_id\": \"COP\"  },  {    \"id\": \"CR\",    \"name\": \"Costa Rica\",    \"locale\": \"es_CR\",    \"currency_id\": \"CRC\"  },  {    \"id\": \"CL\",    \"name\": \"Chile\",    \"locale\": \"es_CL\",    \"currency_id\": \"CLP\"  },  {    \"id\": \"EC\",    \"name\": \"Ecuador\",    \"locale\": \"es_EC\",    \"currency_id\": \"USD\"  },  {    \"id\": \"MX\",    \"name\": \"Mexico\",    \"locale\": \"es_MX\",    \"currency_id\": \"MXN\"  },  {    \"id\": \"PA\",    \"name\": \"Panamá\",    \"locale\": \"es_PA\",    \"currency_id\": \"USD\"  },  {    \"id\": \"PE\",    \"name\": \"Peru\",    \"locale\": \"es_PE\",    \"currency_id\": \"PEN\"  },  {    \"id\": \"PT\",    \"name\": \"Portugal\",    \"locale\": \"pt_PT\",    \"currency_id\": \"EUR\"  },  {    \"id\": \"DO\",    \"name\": \"República Dominicana\",    \"locale\": \"es_DO\",    \"currency_id\": \"DOP\"  },  {    \"id\": \"UY\",    \"name\": \"Uruguay\",    \"locale\": \"es_UY\",    \"currency_id\": \"UYU\"  },  {    \"id\": \"VE\",    \"name\": \"Venezuela\",    \"locale\": \"es_VE\",    \"currency_id\": \"VES\"  },  {    \"id\": \"GT\",    \"name\": \"Guatemala\",    \"locale\": \"es_GT\",    \"currency_id\": \"GTQ\"  },  {    \"id\": \"BO\",    \"name\": \"Bolivia\",    \"locale\": \"es_BO\",    \"currency_id\": \"BOB\"  },  {    \"id\": \"HN\",    \"name\": \"Honduras\",    \"locale\": \"es_HN\",    \"currency_id\": \"HNL\"  },  {    \"id\": \"NI\",    \"name\": \"Nicaragua\",    \"locale\": \"es_NI\",    \"currency_id\": \"NIO\"  },  {    \"id\": \"SV\",    \"name\": \"El Salvador\",    \"locale\": \"es_SV\",    \"currency_id\": \"USD\"  },  {    \"id\": \"PR\",    \"name\": \"Puerto Rico\",    \"locale\": \"es_PR\",    \"currency_id\": \"USD\"  },  {    \"id\": \"PY\",    \"name\": \"Paraguay\",    \"locale\": \"es_PY\",    \"currency_id\": \"PYG\"  },  {    \"id\": \"CU\",    \"name\": \"Cuba\",    \"locale\": \"es_CU\",    \"currency_id\": \"CUC\"  }]";
    }

    public static String getCountry(){
        return "{  \"id\": \"AR\",  \"name\": \"Argentina\",  \"locale\": \"es_AR\",  \"currency_id\": \"ARS\",  \"decimal_separator\": \",\",  \"thousands_separator\": \".\",  \"time_zone\": \"GMT-03:00\",  \"geo_information\": {    \"location\": {      \"latitude\": -38.416096,      \"longitude\": -63.616673    }  },  \"states\": [\n    {\n      \"id\": \"AR-B\",\n      \"name\": \"Buenos Aires\"\n    },\n    {\n      \"id\": \"AR-C\",\n      \"name\": \"Capital Federal\"\n    },\n    {\n      \"id\": \"AR-K\",\n      \"name\": \"Catamarca\"\n    },\n    {\n      \"id\": \"AR-H\",\n      \"name\": \"Chaco\"\n    },\n    {\n      \"id\": \"AR-U\",\n      \"name\": \"Chubut\"\n    },\n    {\n      \"id\": \"AR-W\",\n      \"name\": \"Corrientes\"\n    },\n    {\n      \"id\": \"AR-X\",\n      \"name\": \"Córdoba\"\n    },\n    {\n      \"id\": \"AR-E\",\n      \"name\": \"Entre Ríos\"\n    },\n    {\n      \"id\": \"AR-P\",\n      \"name\": \"Formosa\"\n    },\n    {\n      \"id\": \"AR-Y\",\n      \"name\": \"Jujuy\"\n    },\n    {\n      \"id\": \"AR-L\",\n      \"name\": \"La Pampa\"\n    },\n    {\n      \"id\": \"AR-F\",\n      \"name\": \"La Rioja\"\n    },\n    {\n      \"id\": \"AR-M\",\n      \"name\": \"Mendoza\"\n    },\n    {\n      \"id\": \"AR-N\",\n      \"name\": \"Misiones\"\n    },\n    {\n      \"id\": \"AR-Q\",\n      \"name\": \"Neuquén\"\n    },\n    {\n      \"id\": \"AR-R\",\n      \"name\": \"Río Negro\"\n    },\n    {\n      \"id\": \"AR-A\",\n      \"name\": \"Salta\"\n    },\n    {\n      \"id\": \"AR-J\",\n      \"name\": \"San Juan\"\n    },\n    {\n      \"id\": \"AR-D\",\n      \"name\": \"San Luis\"\n    },\n    {\n      \"id\": \"AR-Z\",\n      \"name\": \"Santa Cruz\"\n    },\n    {\n      \"id\": \"AR-S\",\n      \"name\": \"Santa Fe\"\n    },\n    {\n      \"id\": \"AR-G\",\n      \"name\": \"Santiago del Estero\"\n    },\n    {\n      \"id\": \"AR-V\",\n      \"name\": \"Tierra del Fuego\"\n    },\n    {\n      \"id\": \"AR-T\",\n      \"name\": \"Tucumán\"\n    }\n  ]\n}";
    }
}
